### ISSUE TITLE
File `MeniItem.kt` should presumably be `MenuItem.kt`

### ISSUE THREAD

**Issue by ElectricMagic** [tkuenneth/BeNice#1]
File `MeniItem.kt` should presumably be `MenuItem.kt`. Being a neat freak:)

**Comment by tkuenneth** [comment]
Hey, thanks for spotting this typo. Yes, will fix this

**Comment by tkuenneth** [comment]
Fixed. https://github.com/tkuenneth/BeNice/commit/077c8a8d243eeed4cb5eec1d0506fe9cf5284d5b
